name: Deploying Web servers using Terraform and Github ACtions

on:
  push:
    branches:
      - Feature-A

  pull_request:
    types: [closed]
    branches:
      - main
      - Feature-B

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.9
      - name: Format Terraform code
        run: terraform fmt 
        working-directory: ./

  plan:
    needs: lint
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Feature-a'
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform init
        run: terraform init
        working-directory: ./
      - name: Terraform plan
        working-directory: ./
        run: terraform plan 

  apply:
    needs: lint
    runs-on: ubuntu-latest
    if: |
      github.ref == 'main' &&
      github.event.pull_request.merged == true
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform init
        run: terraform init
        working-directory: ./
      - name: Terraform Apply
        working-directory: ./
        run: terraform apply -auto-approve 

  destroy:
    needs: lint
    runs-on: ubuntu-latest
    if: |
      github.ref == 'Feature-B' &&
      github.event.pull_request.merged == true
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform init
        run: terraform init
        working-directory: ./
      - name: Terraform Destroy
        working-directory: ./
        run: terraform destroy -auto-approve